/**
 * ====================================================================
 * IDP ROLE-BASED E-COMMERCE WEB APPLICATION
 * DATABASE SEEDER — ORACLE MODE
 * ====================================================================
 *
 * Generates correct PBKDF2 hashes at runtime using the SAME
 * cryptoUtils.hashPassword() function used during normal registration.
 * This guarantees seeded users and manually-registered users use
 * identical hashing logic — zero mismatch.
 *
 * Usage:
 *   Automatic: Called by server.js on every startup (idempotent — safe
 *              to run repeatedly; skips users that already exist).
 *   Manual:    node server/database/seeder.js
 */

const cryptoUtils = require('../utils/cryptoUtils');

// Canonical seed definitions — plaintext passwords hashed at runtime
const SEED_ROLES = [
    { id: 1, name: 'Admin' },
    { id: 2, name: 'Seller' },
    { id: 3, name: 'Customer' },
    { id: 4, name: 'Service Team' }
];

const SEED_USERS = [
    {
        id: 1, username: 'admin',    plainPassword: 'admin123',
        email: 'admin@idpshop.edu',  role_id: 1,
        full_name: 'System Administrator', is_active: 1
    },
    {
        id: 2, username: 'seller',   plainPassword: 'seller123',
        email: 'seller@idpshop.edu', role_id: 2,
        full_name: 'Elite Campus Seller',  is_active: 1
    },
    {
        id: 3, username: 'customer', plainPassword: 'customer123',
        email: 'customer@idpshop.edu', role_id: 3,
        full_name: 'John Doe Student',    is_active: 1
    },
    {
        id: 4, username: 'service',  plainPassword: 'service123',
        email: 'service@idpshop.edu', role_id: 4,
        full_name: 'Operations Coordinator', is_active: 1
    }
];

const SEED_CATEGORIES = [
    { id: 1, name: 'Electronics', description: 'Gadgets, devices, and electronic accessories.', icon: 'laptop', is_active: 1 },
    { id: 2, name: 'Clothing', description: 'University apparel and campus fashion.', icon: 'tshirt', is_active: 1 },
    { id: 3, name: 'Books', description: 'Academic textbooks and reading materials.', icon: 'book', is_active: 1 },
    { id: 4, name: 'Lab Equipment', description: 'Scientific tools and lab experiment kits.', icon: 'flask', is_active: 1 },
    { id: 5, name: 'Stationery', description: 'Notebooks, pens, and study supplies.', icon: 'pen', is_active: 1 },
    { id: 6, name: 'Sports', description: 'Fitness gear and sports equipment.', icon: 'dumbbell', is_active: 1 },
    { id: 7, name: 'Home & Living', description: 'Dorm room decor and home goods.', icon: 'home', is_active: 1 },
    { id: 8, name: 'Accessories', description: 'Bags, watches, and daily essentials.', icon: 'gem', is_active: 1 }
];

const SEED_PRODUCTS = [
    {
        id: 1, seller_id: 2,
        name: 'Engineering Toolkit v3',
        description: 'Complete kit including digital multimeter, breadboard, wire strippers, and microcontrollers for electrical laboratory classes.',
        price: 45.99, stock: 50, is_active: 1,
        category_id: 4, image_url: '/uploads/products/placeholder-toolkit.png'
    },
    {
        id: 2, seller_id: 2,
        name: 'Mechanical Drafting Instrument',
        description: 'Professional-grade technical drawing compass set with extension bars, dividers, and precision mechanical lead pens.',
        price: 29.50, stock: 35, is_active: 1,
        category_id: 5, image_url: '/uploads/products/placeholder-drafting.png'
    },
    {
        id: 3, seller_id: 2,
        name: 'University Hooded Sweatshirt',
        description: 'Extra comfort navy blue university design lab hoodie, premium heavy cotton blend.',
        price: 39.99, stock: 120, is_active: 1,
        category_id: 2, image_url: '/uploads/products/placeholder-sweatshirt.png'
    },
    {
        id: 4, seller_id: 2,
        name: 'Reusable Lab Notebook',
        description: 'Synthetically designed spiral smart notebook, dot grid layout, microfiber cloth included.',
        price: 18.00, stock: 200, is_active: 1,
        category_id: 5, image_url: '/uploads/products/placeholder-notebook.png'
    }
];

// -----------------------------------------------------------------------
// ORACLE DB SEEDER
// -----------------------------------------------------------------------
async function seedOracle(db) {
    console.log('\x1b[36m%s\x1b[0m', '>> [Seeder] Running Oracle DB schema migrations & seed checks...');

    // 1. Schema migration checks
    try {
        const rows = await db.query("SELECT table_name FROM user_tables WHERE table_name = 'CATEGORIES'");
        if (rows.length === 0) {
            console.log('   >> [Migrator] Table CATEGORIES is missing. Creating...');
            await db.execute(`
                CREATE TABLE categories (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(100) NOT NULL UNIQUE,
                    description VARCHAR2(500),
                    icon VARCHAR2(50),
                    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
                )
            `);
            console.log('   >> [Migrator] Table CATEGORIES created.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to check/create CATEGORIES table:', e.message);
    }

    try {
        const rows = await db.query("SELECT table_name FROM user_tables WHERE table_name = 'REVIEWS'");
        if (rows.length === 0) {
            console.log('   >> [Migrator] Table REVIEWS is missing. Creating...');
            await db.execute(`
                CREATE TABLE reviews (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    product_id NUMBER NOT NULL,
                    customer_id NUMBER NOT NULL,
                    rating NUMBER(1) NOT NULL CHECK (rating BETWEEN 1 AND 5),
                    review_text VARCHAR2(1000),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT uq_product_customer UNIQUE (product_id, customer_id)
                )
            `);
            try {
                await db.execute('CREATE INDEX idx_reviews_product ON reviews(product_id)');
            } catch (idxErr) {}
            console.log('   >> [Migrator] Table REVIEWS created.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to check/create REVIEWS table:', e.message);
    }

    try {
        const cols = await db.query("SELECT column_name FROM user_tab_columns WHERE table_name = 'PRODUCTS' AND column_name IN ('CATEGORY_ID', 'IMAGE_URL')");
        const existingCols = cols.map(c => c.COLUMN_NAME.toUpperCase());
        
        if (!existingCols.includes('CATEGORY_ID')) {
            console.log('   >> [Migrator] Column category_id is missing from products. Altering...');
            await db.execute('ALTER TABLE products ADD category_id NUMBER');
            await db.execute('ALTER TABLE products ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL');
            console.log('   >> [Migrator] Column category_id added to products.');
        }
        
        if (!existingCols.includes('IMAGE_URL')) {
            console.log('   >> [Migrator] Column image_url is missing from products. Altering...');
            await db.execute('ALTER TABLE products ADD image_url VARCHAR2(500)');
            console.log('   >> [Migrator] Column image_url added to products.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to check/alter products columns:', e.message);
    }

    // --- v2 MIGRATIONS: users new columns ---
    try {
        const uCols = await db.query("SELECT column_name FROM user_tab_columns WHERE table_name = 'USERS' AND column_name IN ('PHONE_NUMBER','ADDRESS','AVATAR_URL')");
        const existing = uCols.map(c => c.COLUMN_NAME.toUpperCase());
        if (!existing.includes('PHONE_NUMBER')) {
            await db.execute('ALTER TABLE users ADD phone_number VARCHAR2(20)');
            console.log('   >> [Migrator] Column phone_number added to users.');
        }
        if (!existing.includes('ADDRESS')) {
            await db.execute('ALTER TABLE users ADD address VARCHAR2(500)');
            console.log('   >> [Migrator] Column address added to users.');
        }
        if (!existing.includes('AVATAR_URL')) {
            await db.execute('ALTER TABLE users ADD avatar_url VARCHAR2(500)');
            console.log('   >> [Migrator] Column avatar_url added to users.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to migrate users columns:', e.message);
    }

    // --- v2 MIGRATIONS: orders new columns ---
    try {
        const oCols = await db.query("SELECT column_name FROM user_tab_columns WHERE table_name = 'ORDERS' AND column_name IN ('PAYMENT_METHOD','PAYMENT_STATUS','TRANSACTION_ID','SHIPPING_NAME','SHIPPING_PHONE','SHIPPING_ADDRESS')");
        const existing = oCols.map(c => c.COLUMN_NAME.toUpperCase());
        if (!existing.includes('PAYMENT_METHOD'))  { await db.execute("ALTER TABLE orders ADD payment_method VARCHAR2(50)");  console.log('   >> [Migrator] Column payment_method added.'); }
        if (!existing.includes('PAYMENT_STATUS'))  { await db.execute("ALTER TABLE orders ADD payment_status VARCHAR2(50)");  console.log('   >> [Migrator] Column payment_status added.'); }
        if (!existing.includes('TRANSACTION_ID'))  { await db.execute("ALTER TABLE orders ADD transaction_id VARCHAR2(100)"); console.log('   >> [Migrator] Column transaction_id added.'); }
        if (!existing.includes('SHIPPING_NAME'))   { await db.execute("ALTER TABLE orders ADD shipping_name VARCHAR2(100)"); console.log('   >> [Migrator] Column shipping_name added.'); }
        if (!existing.includes('SHIPPING_PHONE'))  { await db.execute("ALTER TABLE orders ADD shipping_phone VARCHAR2(20)"); console.log('   >> [Migrator] Column shipping_phone added.'); }
        if (!existing.includes('SHIPPING_ADDRESS')){ await db.execute("ALTER TABLE orders ADD shipping_address VARCHAR2(500)"); console.log('   >> [Migrator] Column shipping_address added.'); }
    } catch (e) {
        console.error('   >> [Migrator] Failed to migrate orders columns:', e.message);
    }

    // --- v2 MIGRATIONS: password_reset_tokens table ---
    try {
        const tRows = await db.query("SELECT table_name FROM user_tables WHERE table_name = 'PASSWORD_RESET_TOKENS'");
        if (tRows.length === 0) {
            await db.execute(`
                CREATE TABLE password_reset_tokens (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id NUMBER NOT NULL,
                    token_hash VARCHAR2(256) NOT NULL,
                    expires_at TIMESTAMP NOT NULL,
                    used NUMBER(1) DEFAULT 0 CHECK (used IN (0,1)),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
            `);
            console.log('   >> [Migrator] Table password_reset_tokens created.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to create password_reset_tokens table:', e.message);
    }

    // --- v2 MIGRATIONS: wishlist table ---
    try {
        const wRows = await db.query("SELECT table_name FROM user_tables WHERE table_name = 'WISHLIST'");
        if (wRows.length === 0) {
            await db.execute(`
                CREATE TABLE wishlist (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id NUMBER NOT NULL,
                    product_id NUMBER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_wishlist_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                    CONSTRAINT uq_wishlist UNIQUE (customer_id, product_id)
                )
            `);
            console.log('   >> [Migrator] Table wishlist created.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to create wishlist table:', e.message);
    }

    // --- v2 MIGRATIONS: recently_viewed table ---
    try {
        const rvRows = await db.query("SELECT table_name FROM user_tables WHERE table_name = 'RECENTLY_VIEWED'");
        if (rvRows.length === 0) {
            await db.execute(`
                CREATE TABLE recently_viewed (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id NUMBER NOT NULL,
                    product_id NUMBER NOT NULL,
                    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_rv_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT fk_rv_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
                )
            `);
            console.log('   >> [Migrator] Table recently_viewed created.');
        }
    } catch (e) {
        console.error('   >> [Migrator] Failed to create recently_viewed table:', e.message);
    }

    // 2. Seed roles (skip existing)
    for (const role of SEED_ROLES) {
        try {
            const existing = await db.query(
                'SELECT id FROM roles WHERE id = :1', [role.id]
            );
            if (existing.length === 0) {
                await db.execute(
                    'INSERT INTO roles (id, name) VALUES (:1, :2)',
                    [role.id, role.name]
                );
                console.log(`   >> [Seeder] Inserted role: ${role.name}`);
            }
        } catch (e) {
            console.warn(`   >> [Seeder] Role seed warning for "${role.name}": ${e.message}`);
        }
    }

    // 3. Seed users — hash each plaintext password fresh at runtime
    for (const u of SEED_USERS) {
        try {
            const existing = await db.query(
                'SELECT id, password_hash FROM users WHERE LOWER(username) = :1', [u.username.toLowerCase()]
            );
            if (existing.length === 0) {
                const hashedPw = cryptoUtils.hashPassword(u.plainPassword);
                await db.execute(
                    `INSERT INTO users (id, username, password_hash, email, role_id, full_name, is_active)
                     VALUES (:1, :2, :3, :4, :5, :6, :7)`,
                    [u.id, u.username, hashedPw, u.email, u.role_id, u.full_name, u.is_active]
                );
                console.log(`\x1b[32m   >> [Seeder] Seeded user: ${u.username} (role_id=${u.role_id})\x1b[0m`);
            } else {
                const row = existing[0];
                const storedHash = row.PASSWORD_HASH;
                const passwordOk = cryptoUtils.verifyPassword(u.plainPassword, storedHash);
                if (!passwordOk) {
                    const hashedPw = cryptoUtils.hashPassword(u.plainPassword);
                    await db.execute(
                        'UPDATE users SET password_hash = :1 WHERE id = :2',
                        [hashedPw, Number(row.ID)]
                    );
                    console.log(`\x1b[33m   >> [Seeder] Oracle: Patched stale hash for user "${u.username}"\x1b[0m`);
                } else {
                    console.log(`   >> [Seeder] User "${u.username}" already exists & hash OK — skipping.`);
                }
            }
        } catch (e) {
            console.warn(`   >> [Seeder] User seed warning for "${u.username}": ${e.message}`);
        }
    }

    // 4. Seed categories
    for (const cat of SEED_CATEGORIES) {
        try {
            const existing = await db.query('SELECT id FROM categories WHERE id = :1', [cat.id]);
            if (existing.length === 0) {
                await db.execute(
                    'INSERT INTO categories (id, name, description, icon, is_active) VALUES (:1, :2, :3, :4, :5)',
                    [cat.id, cat.name, cat.description, cat.icon, cat.is_active]
                );
                console.log(`   >> [Seeder] Inserted category: ${cat.name}`);
            }
        } catch (e) {
            console.warn(`   >> [Seeder] Category seed warning for "${cat.name}": ${e.message}`);
        }
    }

    // 5. Seed products
    for (const p of SEED_PRODUCTS) {
        try {
            const existing = await db.query(
                'SELECT id, category_id, image_url FROM products WHERE id = :1', [p.id]
            );
            if (existing.length === 0) {
                await db.execute(
                    `INSERT INTO products (id, seller_id, name, description, price, stock, is_active, category_id, image_url)
                     VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)`,
                    [p.id, p.seller_id, p.name, p.description, p.price, p.stock, p.is_active, p.category_id, p.image_url]
                );
                console.log(`   >> [Seeder] Inserted product: ${p.name}`);
            } else {
                const row = existing[0];
                if (row.CATEGORY_ID === null || row.IMAGE_URL === null) {
                    await db.execute(
                        'UPDATE products SET category_id = :1, image_url = :2 WHERE id = :3',
                        [p.category_id, p.image_url, p.id]
                    );
                    console.log(`   >> [Seeder] Oracle: Patched category_id and image_url for product "${p.name}"`);
                }
            }
        } catch (e) {
            console.warn(`   >> [Seeder] Product seed warning for "${p.name}": ${e.message}`);
        }
    }

    console.log('\x1b[32m%s\x1b[0m', '>> [Seeder] Oracle seed check complete.');
}

// -----------------------------------------------------------------------
// MOCK DB SEEDER (re-seeds in-memory store if hashes are stale)
// -----------------------------------------------------------------------
function seedMock(mockDb) {
    console.log('\x1b[36m%s\x1b[0m', '>> [Seeder] Verifying MockDB seed integrity...');

    // Seed roles
    for (const r of SEED_ROLES) {
        const existing = mockDb.selectOne('roles', x => x.id === r.id);
        if (!existing) {
            mockDb.insert('roles', r);
        }
    }

    // Seed users
    for (const u of SEED_USERS) {
        const existing = mockDb.selectOne('users', x => x.username.toLowerCase() === u.username.toLowerCase());
        if (!existing) {
            const hashedPw = cryptoUtils.hashPassword(u.plainPassword);
            mockDb.insert('users', {
                id: u.id, username: u.username, password_hash: hashedPw,
                email: u.email, role_id: u.role_id,
                full_name: u.full_name, is_active: u.is_active,
                phone_number: null, address: null, avatar_url: null
            });
            console.log(`\x1b[32m   >> [Seeder] Mock: Inserted user "${u.username}"\x1b[0m`);
        } else {
            const passwordOk = cryptoUtils.verifyPassword(u.plainPassword, existing.password_hash);
            if (!passwordOk) {
                const hashedPw = cryptoUtils.hashPassword(u.plainPassword);
                mockDb.update(
                    'users',
                    x => x.username.toLowerCase() === u.username.toLowerCase(),
                    { password_hash: hashedPw }
                );
                console.log(`\x1b[33m   >> [Seeder] Mock: Patched stale hash for user "${u.username}"\x1b[0m`);
            }
            // Patch v2 fields if missing
            if (existing.phone_number === undefined || existing.avatar_url === undefined) {
                mockDb.update('users', x => x.id === existing.id, {
                    phone_number: existing.phone_number || null,
                    address: existing.address || null,
                    avatar_url: existing.avatar_url || null
                });
            }
        }
    }

    // Seed categories
    for (const c of SEED_CATEGORIES) {
        const existing = mockDb.selectOne('categories', x => x.id === c.id);
        if (!existing) {
            mockDb.insert('categories', c);
            console.log(`\x1b[32m   >> [Seeder] Mock: Inserted category "${c.name}"\x1b[0m`);
        }
    }

    // Seed products
    for (const p of SEED_PRODUCTS) {
        const existing = mockDb.selectOne('products', x => x.id === p.id);
        if (!existing) {
            mockDb.insert('products', p);
            console.log(`\x1b[32m   >> [Seeder] Mock: Inserted product "${p.name}"\x1b[0m`);
        } else {
            if (existing.category_id === undefined || existing.image_url === undefined) {
                mockDb.update('products', x => x.id === p.id, {
                    category_id: p.category_id,
                    image_url: p.image_url
                });
                console.log(`\x1b[33m   >> [Seeder] Mock: Patched category_id and image_url for product "${p.name}"\x1b[0m`);
            }
        }
    }

    console.log('\x1b[32m%s\x1b[0m', '>> [Seeder] MockDB seed verification complete.');
}

// -----------------------------------------------------------------------
// Main export — called by server.js after db.initialize()
// -----------------------------------------------------------------------
module.exports = {
    async run(db) {
        if (db.isMockMode()) {
            seedMock(db.getMock());
        } else {
            await seedOracle(db);
        }
    }
};

// -----------------------------------------------------------------------
// Allow running directly: node server/database/seeder.js
// -----------------------------------------------------------------------
if (require.main === module) {
    const db = require('./connection');
    (async () => {
        await db.initialize();
        const seeder = module.exports;
        await seeder.run(db);
        console.log('>> [Seeder] Manual seed run complete.');
        process.exit(0);
    })();
}
