-- ====================================================================
-- DESIGN AND DEVELOPMENT OF A ROLE-BASED E-COMMERCE WEB APPLICATION
-- UNIVERSITY INTEGRATED DESIGN PROJECT (IDP) - ORACLE SQL SCHEMA
-- ====================================================================

-- 1. DROP TABLES (IN REVERSE DEPENDENCY ORDER)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE recently_viewed CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE wishlist CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE password_reset_tokens CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE messages CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE notifications CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE warehouse CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE deliveries CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE reviews CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE roles CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ====================================================================
-- 2. CREATE TABLES WITH CONSTRAINTS AND IDENTITY KEYS (ORACLE 12C+)
-- ====================================================================

-- ROLES TABLE
CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- USERS TABLE
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(256) NOT NULL, -- Format: salt.hash
    email VARCHAR2(100) NOT NULL UNIQUE,
    role_id NUMBER NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    phone_number VARCHAR2(20),
    address VARCHAR2(500),
    avatar_url VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- CATEGORIES TABLE
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500),
    icon VARCHAR2(50),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
);

-- PRODUCTS TABLE
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id NUMBER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    description VARCHAR2(1000),
    price NUMBER(10, 2) NOT NULL CHECK (price >= 0),
    stock NUMBER NOT NULL CHECK (stock >= 0),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ALTER PRODUCTS to add image_url and category_id references
ALTER TABLE products ADD (
    category_id NUMBER,
    image_url VARCHAR2(500)
);

ALTER TABLE products ADD CONSTRAINT fk_products_category 
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;

-- REVIEWS TABLE
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    rating NUMBER(1) NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_product_customer UNIQUE (product_id, customer_id)
);

-- ORDERS TABLE
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    total_amount NUMBER(10, 2) NOT NULL CHECK (total_amount >= 0),
    status VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    -- Status values: PENDING, APPROVED, REJECTED, DELIVERED_TO_WAREHOUSE, VERIFIED_IN_WAREHOUSE, DISPATCHED, COMPLETED
    payment_method VARCHAR2(50),
    payment_status VARCHAR2(50),
    transaction_id VARCHAR2(100),
    shipping_name VARCHAR2(100),
    shipping_phone VARCHAR2(20),
    shipping_address VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users(id)
);

-- ORDER_ITEMS TABLE
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    price NUMBER(10, 2) NOT NULL CHECK (price >= 0),
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- DELIVERIES TABLE
CREATE TABLE deliveries (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL UNIQUE,
    status VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    -- Status values: PENDING, IN_TRANSIT, ARRIVED_AT_WAREHOUSE, VERIFIED, DISPATCHED, DELIVERED
    assigned_service_id NUMBER,
    warehouse_arrival_date TIMESTAMP,
    dispatch_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_deliveries_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_deliveries_service FOREIGN KEY (assigned_service_id) REFERENCES users(id) ON DELETE SET NULL
);

-- WAREHOUSE TABLE
CREATE TABLE warehouse (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity >= 0),
    location VARCHAR2(100) DEFAULT 'Aisle-A' NOT NULL,
    verified_status VARCHAR2(50) DEFAULT 'PENDING' NOT NULL, -- PENDING, VERIFIED, DISCREPANCY
    verified_by NUMBER,
    verified_at TIMESTAMP,
    CONSTRAINT fk_warehouse_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_warehouse_verifier FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL
);

-- NOTIFICATIONS TABLE
CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    message VARCHAR2(500) NOT NULL,
    is_read NUMBER(1) DEFAULT 0 CHECK (is_read IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- MESSAGES TABLE (Service team acts as a bridge; customer/seller can only converse via service)
CREATE TABLE messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id NUMBER NOT NULL,
    receiver_id NUMBER NOT NULL,
    order_id NUMBER NOT NULL,
    message_text VARCHAR2(1000) NOT NULL,
    is_service_bridge NUMBER(1) DEFAULT 1 CHECK (is_service_bridge IN (0, 1)), -- Indicates if routed through service
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- PASSWORD_RESET_TOKENS TABLE
CREATE TABLE password_reset_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    token_hash VARCHAR2(256) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used NUMBER(1) DEFAULT 0 CHECK (used IN (0,1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- WISHLIST TABLE
CREATE TABLE wishlist (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlist_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_wishlist UNIQUE (customer_id, product_id)
);

-- RECENTLY_VIEWED TABLE
CREATE TABLE recently_viewed (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rv_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_rv_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);


-- ====================================================================
-- 3. INDEXES FOR OPTIMIZED ROLE-BASED ACCESS & DISPATCH SEARCHING
-- ====================================================================
CREATE INDEX idx_users_role ON users(role_id);
CREATE INDEX idx_products_seller ON products(seller_id);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_deliveries_order ON deliveries(order_id);
CREATE INDEX idx_messages_order ON messages(order_id);
CREATE INDEX idx_reviews_product ON reviews(product_id);

-- ====================================================================
-- 4. SEED SAMPLE RECORDS
-- ====================================================================

-- Roles definition
INSERT INTO roles (id, name) VALUES (1, 'Admin');
INSERT INTO roles (id, name) VALUES (2, 'Seller');
INSERT INTO roles (id, name) VALUES (3, 'Customer');
INSERT INTO roles (id, name) VALUES (4, 'Service Team');

-- Seed Users (Passwords are pre-hashed using PBKDF2-SHA512. Password value for all is '<role>123')
-- For example, admin's password is 'admin123', seller's is 'seller123', customer's is 'customer123', service's is 'service123'
-- Hash format: salt.hash. Salt: "f1a8e2d3b4c56789" (Hexadecimal representation)
-- PBKDF2 hash of admin123 with salt f1a8e2d3b4c56789 (1000 iter, 64-byte key):
-- admin123  -> f1a8e2d3b4c56789.b099d79cc3eb3ca1c8805ad02d707abaa8a1a0465525b2dbc0f73611e35135af0242030c1e5caccd19cfac2221266fc20b71dbfc0c4a934e735c74c24a4ee22f
-- seller123 -> f1a8e2d3b4c56789.208b59137e77eac2d9f55ab20093053adec0625d2fcf5cb8925d9e2b3420f9ece15aa0fc43334189fe0470d49b81862b7b1f91d0e39d2ec1eca018dabd5aaa4f
-- customer123 -> f1a8e2d3b4c56789.fa559ff94d44c698d06f79091d3c9c5dfdca94df0ef7e7faf73a642cd6e8340b7ac64beacdaa2e3a6c5cc564c8d109e77963e5f9091fe7897866254c59f80b68
-- service123 -> f1a8e2d3b4c56789.4f4333ee61e4302420ffeb89b8e0ddb0f680e066adedb1862c1b7d13fa530227a213a6b00530543d8c22e7448be27693c9de6201520a624fcd8fc3804157fdd8

INSERT INTO users (id, username, password_hash, email, role_id, full_name, is_active)
VALUES (1, 'admin', 'f1a8e2d3b4c56789.b099d79cc3eb3ca1c8805ad02d707abaa8a1a0465525b2dbc0f73611e35135af0242030c1e5caccd19cfac2221266fc20b71dbfc0c4a934e735c74c24a4ee22f', 'admin@idpshop.edu', 1, 'System Administrator', 1);

INSERT INTO users (id, username, password_hash, email, role_id, full_name, is_active)
VALUES (2, 'seller', 'f1a8e2d3b4c56789.208b59137e77eac2d9f55ab20093053adec0625d2fcf5cb8925d9e2b3420f9ece15aa0fc43334189fe0470d49b81862b7b1f91d0e39d2ec1eca018dabd5aaa4f', 'seller@idpshop.edu', 2, 'Elite Campus Seller', 1);

INSERT INTO users (id, username, password_hash, email, role_id, full_name, is_active)
VALUES (3, 'customer', 'f1a8e2d3b4c56789.fa559ff94d44c698d06f79091d3c9c5dfdca94df0ef7e7faf73a642cd6e8340b7ac64beacdaa2e3a6c5cc564c8d109e77963e5f9091fe7897866254c59f80b68', 'customer@idpshop.edu', 3, 'John Doe Student', 1);

INSERT INTO users (id, username, password_hash, email, role_id, full_name, is_active)
VALUES (4, 'service', 'f1a8e2d3b4c56789.4f4333ee61e4302420ffeb89b8e0ddb0f680e066adedb1862c1b7d13fa530227a213a6b00530543d8c22e7448be27693c9de6201520a624fcd8fc3804157fdd8', 'service@idpshop.edu', 4, 'Operations Coordinator', 1);

-- Seed Categories
INSERT INTO categories (id, name, description, icon, is_active) VALUES (1, 'Electronics', 'Gadgets, devices, and electronic accessories.', 'laptop', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (2, 'Clothing', 'University apparel and campus fashion.', 'tshirt', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (3, 'Books', 'Academic textbooks and reading materials.', 'book', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (4, 'Lab Equipment', 'Scientific tools and lab experiment kits.', 'flask', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (5, 'Stationery', 'Notebooks, pens, and study supplies.', 'pen', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (6, 'Sports', 'Fitness gear and sports equipment.', 'dumbbell', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (7, 'Home & Living', 'Dorm room decor and home goods.', 'home', 1);
INSERT INTO categories (id, name, description, icon, is_active) VALUES (8, 'Accessories', 'Bags, watches, and daily essentials.', 'gem', 1);

-- Seed Products for instant display
INSERT INTO products (id, seller_id, name, description, price, stock, is_active, category_id, image_url)
VALUES (1, 2, 'Engineering Toolkit v3', 'Complete kit including digital multimeter, breadboard, wire strippers, and microcontrollers for electrical laboratory classes.', 45.99, 50, 1, 4, '/uploads/products/placeholder-toolkit.png');

INSERT INTO products (id, seller_id, name, description, price, stock, is_active, category_id, image_url)
VALUES (2, 2, 'Mechanical Drafting Instrument', 'Professional-grade technical drawing compass set with extension bars, dividers, and precision mechanical lead pens.', 29.50, 35, 1, 5, '/uploads/products/placeholder-drafting.png');

INSERT INTO products (id, seller_id, name, description, price, stock, is_active, category_id, image_url)
VALUES (3, 2, 'University Hooded Sweatshirt', 'Extra comfort navy blue university design lab hoodie, premium heavy cotton blend, ideal for cold computer lab shifts.', 39.99, 120, 1, 2, '/uploads/products/placeholder-sweatshirt.png');

INSERT INTO products (id, seller_id, name, description, price, stock, is_active, category_id, image_url)
VALUES (4, 2, 'Reusable Lab Notebook', 'Synthetically designed spiral smart notebook, dot grid layout, includes microfiber cloth for erasable and uploadable pages.', 18.00, 200, 1, 5, '/uploads/products/placeholder-notebook.png');

COMMIT;
/
